[versions]
junit-jupiter = "5.13.1"
kotlin = "2.1.21"
ktor = "3.2.0"
coroutines = "1.10.2"
serialization = "1.8.1"
logback = "1.5.18"
slf4j = "2.0.17"
dotenv = "3.2.0"
kotlinter = "5.1.1"

[libraries]
# Individual dependencies
dotenv-java = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenv" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

mockk = { module = "io.mockk:mockk", version = "1.14.2" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.2" }

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.3.20" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[bundles]
ktor = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-auth",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-client-logging"
]

kotlinx = [
    "kotlinx-serialization-json",
    "kotlinx-coroutines-core"
]

logging = [
    "slf4j-api",
    "logback-classic"
]

test = [
    "mockk",
    "ktor-client-mock",
    "kotlinx-coroutines-test",
    "junit-jupiter"
]
