name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Add Gradle Properties
        env:
          GITHUB_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GITHUB_PACKAGES_PASSWORD: ${{ secrets.GH_PACKAGES_PASSWORD }}
        run: |
            echo "release.user=${GITHUB_PACKAGES_USER_NAME}" >> gradle.properties
            echo "release.key=${GITHUB_PACKAGES_PASSWORD}" >> gradle.properties

      - name: Publish to GitHub Packages
        run: ./gradlew publish

